#!/usr/bin/env php
<?php

$root = __DIR__;

$target = sprintf('%s/build/%s', __DIR__, 'export.phar');

if (file_exists($target)) {
    unlink($target);
}

$phar = new Phar($target, 0, 'export.phar');
$phar->setAlias('export.phar');
$phar->setSignatureAlgorithm(\Phar::SHA1);
$phar->startBuffering();

$dir = new RecursiveDirectoryIterator($root);
$Iterator = new RecursiveIteratorIterator($dir);
$Regex = new RegexIterator($Iterator, '/^.+\.php$/i', RecursiveRegexIterator::GET_MATCH);

foreach ($Regex as $key => $value) {
    if (stripos($key, 'tests') !== false) continue;
    if (stripos($key, 'Tests') !== false) continue;
    $file = new SplFileInfo($key);
    $path = strtr(str_replace($root.'/', '', $file->getRealPath()), '\\', '/');
    $content = file_get_contents($file);
    if (getenv('DEBUG')) echo "Including file ". $path . "\n";
    $phar->addFromString($path, $content);
}

$stub = file_get_contents(sprintf('%s/src/bootstrap.php', $root));

$phar->setStub($stub);
$phar->stopBuffering();

chmod($target, 0755);
