#!/usr/bin/env php
<?php

$srcRoot = __DIR__.'/src';

$target = sprintf('%s/build/%s', __DIR__, 'export.phar');

if (file_exists($target)) {
    unlink($target);
}

$phar = new Phar($target, 0, 'export.phar');
$phar->setSignatureAlgorithm(\Phar::SHA1);
$phar->startBuffering();

$dir = new RecursiveDirectoryIterator($srcRoot);
$Iterator = new RecursiveIteratorIterator($dir);
$Regex = new RegexIterator($Iterator, '/^.+\.php$/i', RecursiveRegexIterator::GET_MATCH);

foreach ($Regex as $key => $value) {
    if (stripos($key, 'bootstrap.php') !== false) {
        continue;
    }
    $file = new SplFileInfo($key);
    $path = strtr(str_replace($srcRoot.'/', '', $file->getRealPath()), '\\', '/');
    $content = file_get_contents($file);

    $phar->addFromString($path, $content);
}

$stub = file_get_contents(sprintf('%s/bootstrap.php', $srcRoot));

$phar->setStub($stub);
$phar->stopBuffering();

chmod($target, 0755);
