<?php

namespace Cygnus\DrushExport\PMMI;

/**
 * Provides support for exporting from Drupal 7.5x
 *
 * Needs working (as in you can login to admin) site for drush to work
 * from drush repo root: php -d phar.readonly=0 compile
 * from drupal site root (ie /sites/heathcare-informatics/): drush scr $pathToPhar $mongoIp $importConfigKey
 * ie: drush scr ~/environment/base-drush-export-master/build/export.phar [MONGO_IP] [IMPORT_KEY]
 *
 */
class BaseExport extends Export
{
    /**
     * {@inheritdoc}
     */
    protected $configs = [
        'aw'  => [
            'name'      => 'Automation World',
            'database'  => 'drupal_pmmi_aw',
            'uri'       => 'https://www.automationworld.com',
            'Issue'     => [
                'magazine_covers' => 'Magazine\\Issue',                         // magazine cover image, digital edition url
            ],
            'Taxonomy'  => [
                // Shared/common
                'Company Type'              => 'Taxonomy\Bin',          // ~ 5 items
                'Source Type'               => 'Taxonomy\Bin',          // 5 items, used to denote UGC and/or display concerns
                'Subtype'                   => 'Taxonomy\Bin',          // 12 items, used to determine article sub type
                'Coverage Type'             => 'Taxonomy\Coverage',     // 20+ items, Similar to website sections?
                'Tags'                      => 'Taxonomy\Tag',
                // AW-specific
                'App Platforms/OS'          => 'Taxonomy\Bin',          // ~5 items
                'Blog Beat'                 => 'Taxonomy\Bin',          // ~ 20 items
                'Column Type'               => 'Taxonomy\Bin',          // ~ 10 items
                'Download Subtype'          => 'Taxonomy\Bin',          // 2 items (Tactical Brief, Whitepaper)
                'Industry Type'             => 'Taxonomy\Bin',          // 4 items
                'Leadership Session'        => 'Taxonomy\Bin',          // 5 items, years 2015-2019
                'Automation Strategies'     => 'Taxonomy\Category',     // 100+ items
                'Topics'                    => 'Taxonomy\Topic',        // 11 items
                // New hierarchical types
                'Industries'                => 'Taxonomy\Industries',   // 20+ items (top categories?)
                'Technologies'              => 'Taxonomy\Technology',   // ~50 items, similar to `Industries` taxonomy (if kept, create Technologies instead of Market)
            ],
            'Content'   => [
                '360_package_spin_rotate'   => 'Website\Content\Product',   // Needs some custom field handling for the 3D display
                'apps'                      => 'Website\Content\Product',   // Custom field handling
                'around_the_world'          => 'Website\Content\Article',   // Around the world section/blog
                'article'                   => 'Website\Content\Article',   // Make all Articles by default
                'page'                      => 'Website\Content\Page',
                'blog'                      => 'Website\Content\Blog',
                'company'                   => 'Website\Content\Company',
                'download'                  => 'Website\Content\Document',
                // 'leadership_data_card'                                   // Additional information about companies, unsure where used.
                // 'leadership_online_profile'                              // More info,
                // 'leadership_print_profile'                               // More info, print revision??
                'mini_bant'                 => 'Website\Content\TextAd',    // Sponsored content, gated video/whitepaper landing page
                'playbook'                  => 'Website\Content\Document',  // May necessitate a custom content type, but a gated landing page for a PDF download
                'podcast'                   => 'Website\Content\Podcast',
                'registration_form'         => 'Website\Content\Document',  // Majority appear to be PDF gates (some weird ones like ENL signups)
                'video'                     => 'Website\Content\Video',
                'webinar'                   => 'Website\Content\Webinar',   // All old, currently unpublished
                'webinar_registration'      => 'Website\Content\Webinar',   // Current webinar landing form
                'week_in_review'            => 'Website\Content\News',      // News/sponsored review, "Beyond the Factory Walls" primary section??
                'whitepaper'                => 'Website\Content\Whitepaper',
            ],
            'Section'   => [
                // 'page' => 'Website\\Section',
                // 'page2' => 'Website\\Section',
            ],
            'structure' =>  [
                'stripFields'   => [
                    // These fields will be removed from nodes before being written to mongo
                    'vid',
                    'log',
                    'uuid',
                    'tnid',
                    'cid',                          // comment id
                    'translate',
                    'print_html_display',
                    'print_html_display_comment',
                    'print_html_display_urllist',
                    'last_comment_uid',
                    'last_comment_name',
                    'last_comment_timestamp',
                    'revision_timestamp',           // looks to be same as 'changed' which we are using
                    'revision_uid',
                    'language',                     // language value, (und default)
                    'comment',
                    'comment_count',
                    'promote',
                    'sticky',
                    'vuuid',
                    'rdf_mapping',
                    'path',
                    'metatags',
                    'data',
                    'picture',
                    //'premium_content','comment_count','picture','data'  // other fields I see but leaving for now
                    //'moderate','format','feed','field_priority','field_leagcy_id','rdf_mapping','metatags','field_legacy_article_id');  // fields in old code, but not seen so far in hci
                    'field_360_multi_upload',
                    'field_360_images_reverse',
                    'field_360_magic_plugin',
                    'field_360_magic_plugin_columns',
                    'field_360_magic_plugin_rows',
                    'field_360_images',
                    'field_360_fc_large',
                    'field_gallery_360_field_location',
                    'field_allterms',   // @todo handle in taxonomy segment
                    'field_related',
                    'field_pop_up_registration',
                    'field_joomla_id',
                    'field_accela_id',
                    'field_duplicate',
                    'field_accelaworks_billcode',
                    'field_article_length',
                    'field_app_sponsor_news',
                    'field_brand_override',
                    'field_master_accelaworks_id',
                    'field_master_leadworks_id',
                    'field_form_header',

                    'field_post_launch_banner',
                    'field_pre_launch_banner',
                    'field_promoted',
                    'field_show_site_logo',
                    'field_silverpop_program_id',
                    'field_smg_pop_viddler',
                    'field_social_media_watch',
                    'field_sponsor_links',
                    'field_sponsor_logo',
                    'field_stage_one_form',
                    'field_vocab_primary_industry',
                    'field_vocab_primary',

                    'field_waywire_playlist_id',
                    'field_waywire_tag',
                    'field_waywire_video',
                    'field_webtracking_name',
                    'field_updated_on',
                    'field_top_copy',
                    'field_legacy',
                    'field_crosspost_to_pfw',
                    'field_reporting_from',
                    'webform',
                    'field_sales_reps', // no data

                    // Fields that may be important later, but exist in `legacy.raw`
                    'field_viddler_id',
                    'field_sponsor_expiration',
                    'field_omeda_behavior_ids',
                    'field_omeda_deployment_type_ids',
                    'field_omeda_download_attr_id',
                    'field_omeda_product_ids',
                    'field_omeda_promo_code',
                    'field_pull_quote',
                    'field_pullquote',
                    'field_top_copy',
                    'field_sub_title',
                    'field_app_more_information_link',
                    'field_application_case_history',
                    'field_platforms_os',
                    'field_video_resources', // Exist only on apps, part of the custom data presentation

                    'field_issue_date', // Issue date + page num appear to be references to print scheduling
                    'field_page_num',   // but don't contain enough data to map.


                    // 'field_wir_sponsor',
                    'field_youtube_uploads_id',
                    // 'field_youtube_username',
                    'field_youtube_username_override',

                    // Renamed fields, remove to cleanup
                    'nid',
                    'uid',
                    'title',
                    'field_deckhead',
                    'field_image',
                    'field_article_images',
                    'changed',
                    'field_byline',
                    'field_author_title',
                    // 'field_sub_podcasts',
                    // 'field_whitepaper',
                    // 'field_white_paper',     // Exist on Videos, contain youtube links??
                ],
                '_id'       => 'nid',
                'name'      => 'title',
                'status'    => 'status',
                'createdBy' => 'uid',
                'updatedBy' => 'revision_uid',  // was using uid for both but I changed - ok, or less reliable?  @jpdev
                'created'   => 'created',
                'updated'   => 'changed',
                'published' => 'created',
                'mutations' => 'path',
                'type'      => 'field_term_subtype.und.0.tid',
                'body'      => 'body.und.0.value',
                'teaser'    => 'field_deckhead.und.0.value',
                // 'authors'   => 'field_byline.und.0.value',
                // 'deck'      => 'field_deck.und.0.value',
                'images'    => ['field_image.und', 'field_article_images.und'],
                // // existing fields (used mainly by top100)
                // 'phone'     => 'field_phone.und.0.value',
                // 'city'      => 'field_hci100_location.und.0.value',
                // 'website'   => 'field_website.und.0.value',
                // 'socialLinks'       => ['field_twitter.und.0.value', '	field_linkedin.und.0.value', 'field_facebook.und.0.value'],
                // //'taxonomy'  => 'taxonomy',  // moving taxonomy refs in to legacy.refs from the outset, so not needed here (unless I move convertTaxonomy code into the convertFields method, which might be good)
                // // these are for the new top100 content type
                // 'rank'              => 'field_hci100_rank.und.0.value',
                // 'previousRank'      => 'field_hci100_previous_rank.und.0.value',
                // 'founded'           => 'field_hci100_founded.und.0.value',
                // 'companyType'       => 'field_hci100_company_type.und.0.value',
                // 'employees'         => 'field_hci100_employees.und.0.value',
                // 'revenueCurrent'    => 'field_hci100_revenue_current.und.0.value',
                // 'revenuePrior1'     => 'field_hci100_revenue_prior1.und.0.value',
                // 'revenuePriorYear1' => 'field_hci100_revenue_prior1_yyyy.und.0.value',
                // 'revenuePrior2'     => 'field_hci100_revenue_prior2.und.0.value',
                // 'revenuePriorYear2' => 'field_hci100_revenue_prior2_yyyy.und.0.value',
                // 'companyExecutives' => 'field_hci100_company_executives.und.0.value',
                // 'majorRevenue'      => 'field_hci100_major_revenue.und.0.value',
                // 'productCategories' => 'field_hci100_product_categories.und.0.value',
                // 'marketsServing'    => 'field_hci100_markets_serving.und.0.value',
                // 'linkUrl'           => 'function_getRedirects',
            ],
            'leadership'    => [
                'term_fields'  => [
                    'categories_technologies'
                ],
                'map'   => [
                    '13_2685' => 33199,
                    '13_2686' => 33200,
                    '13_2687' => 33201,
                    '13_2688' => 33203,
                    '13_2755' => 33202,
                    '13_3992' => 33204,
                    '13_2689' => 33205,
                    '13_2690' => 33207,
                    '13_2691' => 33208,
                    '13_2692' => 33206,
                    '13_2693' => 33209,
                    '13_3997' => 33211,
                    '13_2694' => 33212,
                    '13_2695' => 33213,
                    '13_2696' => 33214,
                    '13_2756' => 33215,
                    '13_2697' => 33210,
                    '13_2699' => 33216,
                    '13_2700' => 33217,
                    '13_2698' => 33218,
                    '13_2701' => 33219,
                    '13_2702' => 33220,
                    '13_2703' => 33221,
                    '13_4002' => 33222,
                    '13_2704' => 33224,
                    '13_2705' => 33223,
                    '13_2706' => 33225,
                    '13_2707' => 33226,
                    '13_2708' => 33227,
                    '13_2709' => 33228,
                    '13_2727' => 33228,
                    '13_2728' => 33228,
                    '13_2729' => 33228,
                    '13_2730' => 33228,
                    '13_2733' => 33228,
                    '13_2731' => 33228,
                    '13_2732' => 33228,
                    '13_2734' => 33228,
                    '13_2735' => 33228,
                    '13_2736' => 33228,
                    '13_2737' => 33228,
                    '13_2738' => 33228,
                    '13_2739' => 33228,
                    '13_2740' => 33228,
                    '13_2741' => 33228,
                    '13_2710' => 33229,
                    '13_2711' => 33230,
                    '13_2712' => 33231,
                    '13_2713' => 33232,
                    '13_2714' => 33233,
                    '13_2715' => 33235,
                    '13_2716' => 33234,
                    '13_2718' => 33237,
                    '13_2719' => 33238,
                    '13_2717' => 33236,
                    '13_2720' => 33239,
                    '13_2721' => 33240,
                    '13_2722' => 33241,
                    '13_2723' => 33242,
                    '13_2724' => 33243,
                    '13_2725' => 33244,
                    '13_2726' => 33245,
                    '13_2754' => 33246,
                    '13_3367' => 33247,
                ]
            ]
        ],
        'hp'  => [
            'name'      => 'Healthcare Packaging',
            'database'  => 'drupal_pmmi_hp',
            'uri'       => 'https://www.healthcarepackaging.com',
            'Issue'     => [
                'magazine' => 'Magazine\\Issue',
            ],
            'Taxonomy'  => [
                // Shared/common
                'Company Type'                  => 'Taxonomy\Bin',
                'Media Property'                => 'Taxonomy\Bin',
                'Source type'                   => 'Taxonomy\Bin',
                'Subtype'                       => 'Taxonomy\Bin',
                'Coverage type'                 => 'Taxonomy\Coverage',
                'Tags'                          => 'Taxonomy\Tag',
                'Machinery'                     => 'Taxonomy\Machinery',
                'Material Type'                 => 'Taxonomy\Material',
                'Controls'                      => 'Taxonomy\Controls',
                'Package Component'             => 'Taxonomy\PackageComponent',
                'Package Feature'               => 'Taxonomy\PackageFeature',
                'Package Type'                  => 'Taxonomy\PackageType',
                // HP-specfific
                'Contract Packaging'            => 'Taxonomy\Bin',
                'Line speed'                    => 'Taxonomy\Bin',
                'Machine attributes'            => 'Taxonomy\Bin',
                'Expert - Areas of Expertise'   => 'Taxonomy\Bin',
                'Leadership Session'            => 'Taxonomy\Bin',
                'Premier Categories'            => 'Taxonomy\Bin',
                'Package design'                => 'Taxonomy\Bin',
                'Sustainability'                => 'Taxonomy\Bin',
                'Venue'                         => 'Taxonomy\Bin',
                'Logistics'                     => 'Taxonomy\Bin',
                'Applications'                  => 'Taxonomy\Category',
                'Trends and Issues'             => 'Taxonomy\Topic',
            ],
            'Content'   => [
                '360_package_spin_rotate'   => 'Website\Content\Product',
                'article'                   => 'Website\Content\Article',
                'page'                      => 'Website\Content\Page',
                'company'                   => 'Website\Content\Company',
                'expert'                    => 'Website\Content\Contact',
                'html_content'              => 'Website\Content\Page',
                'registration_form'         => 'Website\Content\Document',
                'video'                     => 'Website\Content\Video',
                'webinar_registration'      => 'Website\Content\Webinar',
                'white_paper'               => 'Website\Content\Whitepaper',
                'playbook'                  => 'Website\Content\Document',
                'podcast'                   => 'Website\Content\Podcast',
                // 'leadership_data_card'
                // 'leadership_online_profile'
                // 'leadership_print_profile'
                // 'premier_supplier_data_card',
            ],
            'Section'   => [],
            'structure' =>  [
                'stripFields'   => [
                    // These fields will be removed from nodes before being written to mongo
                    'vid',
                    'log',
                    'uuid',
                    'tnid',
                    'cid',                          // comment id
                    'translate',
                    'print_html_display',
                    'print_html_display_comment',
                    'print_html_display_urllist',
                    'last_comment_uid',
                    'last_comment_name',
                    'last_comment_timestamp',
                    'revision_timestamp',           // looks to be same as 'changed' which we are using
                    'revision_uid',
                    'language',                     // language value, (und default)
                    'comment',
                    'comment_count',
                    'promote',
                    'sticky',
                    'vuuid',
                    'rdf_mapping',
                    'path',
                    'metatags',
                    'data',
                    'picture',
                    //'premium_content','comment_count','picture','data'  // other fields I see but leaving for now
                    //'moderate','format','feed','field_priority','field_leagcy_id','rdf_mapping','metatags','field_legacy_article_id');  // fields in old code, but not seen so far in hci
                    'field_360_multi_upload',
                    'field_360_images_reverse',
                    'field_360_magic_plugin',
                    'field_360_magic_plugin_columns',
                    'field_360_magic_plugin_rows',
                    'field_360_images',
                    'field_360_fc_large',
                    'field_gallery_360_field_location',
                    'field_allterms',   // @todo handle in taxonomy segment
                    'field_related',
                    'field_pop_up_registration',
                    'field_joomla_id',
                    'field_accela_id',
                    'field_duplicate',
                    'field_accelaworks_billcode',
                    'field_article_length',
                    'field_app_sponsor_news',
                    'field_brand_override',
                    'field_master_accelaworks_id',
                    'field_master_leadworks_id',
                    'field_form_header',

                    'field_post_launch_banner',
                    'field_pre_launch_banner',
                    'field_promoted',
                    'field_show_site_logo',
                    'field_silverpop_program_id',
                    'field_smg_pop_viddler',
                    'field_social_media_watch',
                    'field_sponsor_links',
                    'field_sponsor_logo',
                    'field_stage_one_form',
                    'field_vocab_primary_industry',
                    'field_vocab_primary',

                    'field_waywire_playlist_id',
                    'field_waywire_tag',
                    'field_waywire_video',
                    'field_webtracking_name',
                    'field_updated_on',
                    'field_top_copy',
                    'field_legacy',
                    'field_crosspost_to_pfw',
                    'field_reporting_from',
                    'webform',
                    'field_sales_reps', // no data

                    // Fields that may be important later, but exist in `legacy.raw`
                    'field_viddler_id',
                    'field_sponsor_expiration',
                    'field_omeda_behavior_ids',
                    'field_omeda_deployment_type_ids',
                    'field_omeda_download_attr_id',
                    'field_omeda_product_ids',
                    'field_omeda_promo_code',
                    'field_pull_quote',
                    'field_pullquote',
                    'field_top_copy',
                    'field_sub_title',
                    'field_app_more_information_link',
                    'field_application_case_history',
                    'field_platforms_os',
                    'field_video_resources', // Exist only on apps, part of the custom data presentation

                    'field_issue_date', // Issue date + page num appear to be references to print scheduling
                    'field_page_num',   // but don't contain enough data to map.


                    // 'field_wir_sponsor',
                    'field_youtube_uploads_id',
                    // 'field_youtube_username',
                    'field_youtube_username_override',

                    // Renamed fields, remove to cleanup
                    'nid',
                    'uid',
                    'title',
                    'field_deckhead',
                    'field_image',
                    'field_article_images',
                    'changed',
                    'field_byline',
                    'field_author_title',
                    // 'field_sub_podcasts',
                    // 'field_whitepaper',
                    // 'field_white_paper',     // Exist on Videos, contain youtube links??
                ],
                '_id'       => 'nid',
                'name'      => 'title',
                'status'    => 'status',
                'createdBy' => 'uid',
                'updatedBy' => 'revision_uid',
                'created'   => 'created',
                'updated'   => 'changed',
                'published' => 'created',
            ],
            'leadership'    => [
                'term_fields'  => [
                    'categories'
                ],
                'map'   => [
                    '32_6619' => 33365,
                    '32_6620' => 33364,
                    // '32_7094' => ,
                    '32_6618' => 33363,
                    '32_6617' => 33362,
                    '32_6616' => 33361,
                    '32_6611' => 33354,
                    '32_6610' => 33353,
                    '32_6609' => 33352,
                    '32_6608' => 33351,
                    '32_6802' => 33355,
                    '32_6612' => 33356,
                    '32_6615' => 33360,
                    '32_6614' => 33359,
                    '32_6613' => 33358,
                    '32_6606' => 33357,
                    '32_6607' => 33350,
                ]
            ]
        ],
        'lsl' => [
            'name'      => 'Logistics for the Life Sciences',
            'database'  => 'drupal_pmmi_hp',
            'uri'       => 'https://www.logisticsforthelifesciences.com',
            'Issue'     => [
                'magazine_covers' => 'Magazine\\Issue',
            ],
            'Taxonomy'  => [
                'dont'  => 'map',
                // // Shared/common
                // 'Company Type'                  => 'Taxonomy\Bin',
                // 'Media Property'                => 'Taxonomy\Bin',
                // 'Source type'                   => 'Taxonomy\Bin',
                // 'Subtype'                       => 'Taxonomy\Bin',
                // 'Coverage type'                 => 'Taxonomy\Coverage',
                // // 'Tags'                          => 'Taxonomy\Tag',
                // 'Machinery'                     => 'Taxonomy\Machinery',
                // 'Material Type'                 => 'Taxonomy\Material',
                // 'Controls'                      => 'Taxonomy\Controls',
                // 'Package Component'             => 'Taxonomy\PackageComponent',
                // 'Package Feature'               => 'Taxonomy\PackageFeature',
                // 'Package Type'                  => 'Taxonomy\PackageType',
                // // PW-specific
                // 'Contract packaging'            => 'Taxonomy\Bin',
                // 'Expo Pack Session'             => 'Taxonomy\Bin',
                // 'Gallery Features'              => 'Taxonomy\Bin',
                // 'Gallery Industry'              => 'Taxonomy\Bin',
                // 'Gallery Type'                  => 'Taxonomy\Bin',
                // 'Leadership Main Categories'    => 'Taxonomy\Bin',
                // 'Leadership Session'            => 'Taxonomy\Bin',
                // 'Line speed'                    => 'Taxonomy\Bin',
                // 'Machine attributes'            => 'Taxonomy\Bin',
                // 'Package design'                => 'Taxonomy\Bin',
                // 'Sustainability'                => 'Taxonomy\Bin',
                // 'Venue'                         => 'Taxonomy\Bin',
                // 'Applications'                  => 'Taxonomy\Category',
                // 'Expo Pack Showcase Categories' => 'Taxonomy\ExpoPackShowcaseCategory',
                // 'Leadership Categories'         => 'Taxonomy\LeadershipCategory',
                // 'Trends and Issues'             => 'Taxonomy\Topic',
            ],
            'Content'   => [
                'article'                   => 'Website\Content\Article',
                'company'                   => 'Website\Content\Company',
                'registration_form'         => 'Website\Content\Document',
                'video'                     => 'Website\Content\Video',
                'white_paper'               => 'Website\Content\Whitepaper',
                'page'                      => 'Website\Content\Page',
                'playbook'                  => 'Website\Content\Document',
                'podcast'                   => 'Website\Content\Podcast',
            ],
            'Section'   => [],
            'structure' =>  [
                'stripFields'   => [
                    // These fields will be removed from nodes before being written to mongo
                    'vid',
                    'log',
                    'uuid',
                    'tnid',
                    'cid',                          // comment id
                    'translate',
                    'print_html_display',
                    'print_html_display_comment',
                    'print_html_display_urllist',
                    'last_comment_uid',
                    'last_comment_name',
                    'last_comment_timestamp',
                    'revision_timestamp',           // looks to be same as 'changed' which we are using
                    'revision_uid',
                    'language',                     // language value, (und default)
                    'comment',
                    'comment_count',
                    'promote',
                    'sticky',
                    'vuuid',
                    'rdf_mapping',
                    'path',
                    'metatags',
                    'data',
                    'picture',
                    //'premium_content','comment_count','picture','data'  // other fields I see but leaving for now
                    //'moderate','format','feed','field_priority','field_leagcy_id','rdf_mapping','metatags','field_legacy_article_id');  // fields in old code, but not seen so far in hci
                    'field_360_multi_upload',
                    'field_360_images_reverse',
                    'field_360_magic_plugin',
                    'field_360_magic_plugin_columns',
                    'field_360_magic_plugin_rows',
                    'field_360_images',
                    'field_360_fc_large',
                    'field_gallery_360_field_location',
                    'field_allterms',   // @todo handle in taxonomy segment
                    'field_related',
                    'field_pop_up_registration',
                    'field_joomla_id',
                    'field_accela_id',
                    'field_duplicate',
                    'field_accelaworks_billcode',
                    'field_article_length',
                    'field_app_sponsor_news',
                    'field_brand_override',
                    'field_master_accelaworks_id',
                    'field_master_leadworks_id',
                    'field_form_header',

                    'field_post_launch_banner',
                    'field_pre_launch_banner',
                    'field_promoted',
                    'field_show_site_logo',
                    'field_silverpop_program_id',
                    'field_smg_pop_viddler',
                    'field_social_media_watch',
                    'field_sponsor_links',
                    'field_sponsor_logo',
                    'field_stage_one_form',
                    'field_vocab_primary_industry',
                    'field_vocab_primary',

                    'field_waywire_playlist_id',
                    'field_waywire_tag',
                    'field_waywire_video',
                    'field_webtracking_name',
                    'field_updated_on',
                    'field_top_copy',
                    'field_legacy',
                    'field_crosspost_to_pfw',
                    'field_reporting_from',
                    'webform',
                    'field_sales_reps', // no data

                    // Fields that may be important later, but exist in `legacy.raw`
                    'field_viddler_id',
                    'field_sponsor_expiration',
                    'field_omeda_behavior_ids',
                    'field_omeda_deployment_type_ids',
                    'field_omeda_download_attr_id',
                    'field_omeda_product_ids',
                    'field_omeda_promo_code',
                    'field_pull_quote',
                    'field_pullquote',
                    'field_top_copy',
                    'field_sub_title',
                    'field_app_more_information_link',
                    'field_application_case_history',
                    'field_platforms_os',
                    'field_video_resources', // Exist only on apps, part of the custom data presentation

                    'field_issue_date', // Issue date + page num appear to be references to print scheduling
                    'field_page_num',   // but don't contain enough data to map.


                    // 'field_wir_sponsor',
                    'field_youtube_uploads_id',
                    // 'field_youtube_username',
                    'field_youtube_username_override',

                    // Renamed fields, remove to cleanup
                    'nid',
                    'uid',
                    'title',
                    'field_deckhead',
                    'field_image',
                    'field_article_images',
                    'changed',
                    'field_byline',
                    'field_author_title',
                    // 'field_sub_podcasts',
                    // 'field_whitepaper',
                    // 'field_white_paper',     // Exist on Videos, contain youtube links??
                ],
                '_id'       => 'nid',
                'name'      => 'title',
                'status'    => 'status',
                'createdBy' => 'uid',
                'updatedBy' => 'revision_uid',
                'created'   => 'created',
                'updated'   => 'changed',
                'published' => 'created',
            ],
            'leadership'    => [
                'term_fields'  => [],
                'map'   => []
            ]
        ],
        'oem' => [
            'name'      => 'OEM Magazine',
            'database'  => 'drupal_pmmi_oem',
            'uri'       => 'https://www.oemmagazine.org',
            'Issue'     => [
                'magazine' => 'Magazine\\Issue',
            ],
            'Taxonomy'  => [
                // Shared/common
                'Company Type'                  => 'Taxonomy\Bin',
                'Media Property'                => 'Taxonomy\Bin',
                'Source'                        => 'Taxonomy\Bin',
                'Subtype'                       => 'Taxonomy\Bin',
                'Coverage Type'                 => 'Taxonomy\Coverage',
                'Tags'                          => 'Taxonomy\Tag',
                // OEM-specific
                'Technology Topics'             => 'Taxonomy\Bin',
                'OEM Topics'                    => 'Taxonomy\Bin',
                'Sub-assembly'                  => 'Taxonomy\Bin',
                'Components'                    => 'Taxonomy\Bin',
                'Machine Type'                  => 'Taxonomy\Bin',
                'Products'                      => 'Taxonomy\Category',
                'Trend Setter Session'          => 'Taxonomy\Topic',
            ],
            'Content'   => [
                '360_package_spin_rotate'   => 'Website\Content\Product',
                'article'                   => 'Website\Content\Article',
                'page'                      => 'Website\Content\Page',
                'company'                   => 'Website\Content\Company',
                'registration_form'         => 'Website\Content\Document',
                'video'                     => 'Website\Content\Video',
                'whitepaper'                => 'Website\Content\Whitepaper',
                // 'leadership_data_card'
                // 'leadership_online_profile'
                // 'leadership_print_profile'
                // 'calendar'               // One item, test event, not enabled in drupal UI
                // 'featured_article'       // One item, user-submitted photo gallery from 2016, not published
                // 'magazine'               // Subset of issues, no additional data
            ],
            'Section'   => [],
            'structure' =>  [
                'stripFields'   => [
                    // These fields will be removed from nodes before being written to mongo
                    'vid',
                    'log',
                    'uuid',
                    'tnid',
                    'cid',                          // comment id
                    'translate',
                    'print_html_display',
                    'print_html_display_comment',
                    'print_html_display_urllist',
                    'last_comment_uid',
                    'last_comment_name',
                    'last_comment_timestamp',
                    'revision_timestamp',           // looks to be same as 'changed' which we are using
                    'revision_uid',
                    'language',                     // language value, (und default)
                    'comment',
                    'comment_count',
                    'promote',
                    'sticky',
                    'vuuid',
                    'rdf_mapping',
                    'path',
                    'metatags',
                    'data',
                    'picture',
                    //'premium_content','comment_count','picture','data'  // other fields I see but leaving for now
                    //'moderate','format','feed','field_priority','field_leagcy_id','rdf_mapping','metatags','field_legacy_article_id');  // fields in old code, but not seen so far in hci
                    'field_360_multi_upload',
                    'field_360_images_reverse',
                    'field_360_magic_plugin',
                    'field_360_magic_plugin_columns',
                    'field_360_magic_plugin_rows',
                    'field_360_images',
                    'field_360_fc_large',
                    'field_gallery_360_field_location',
                    'field_allterms',   // @todo handle in taxonomy segment
                    'field_related',
                    'field_pop_up_registration',
                    'field_joomla_id',
                    'field_accela_id',
                    'field_duplicate',
                    'field_accelaworks_billcode',
                    'field_article_length',
                    'field_app_sponsor_news',
                    'field_brand_override',
                    'field_master_accelaworks_id',
                    'field_master_leadworks_id',
                    'field_form_header',

                    'field_post_launch_banner',
                    'field_pre_launch_banner',
                    'field_promoted',
                    'field_show_site_logo',
                    'field_silverpop_program_id',
                    'field_smg_pop_viddler',
                    'field_social_media_watch',
                    'field_sponsor_links',
                    'field_sponsor_logo',
                    'field_stage_one_form',
                    'field_vocab_primary_industry',
                    'field_vocab_primary',

                    'field_waywire_playlist_id',
                    'field_waywire_tag',
                    'field_waywire_video',
                    'field_webtracking_name',
                    'field_updated_on',
                    'field_top_copy',
                    'field_legacy',
                    'field_crosspost_to_pfw',
                    'field_reporting_from',
                    'webform',
                    'field_sales_reps', // no data

                    // Fields that may be important later, but exist in `legacy.raw`
                    'field_viddler_id',
                    'field_sponsor_expiration',
                    'field_omeda_behavior_ids',
                    'field_omeda_deployment_type_ids',
                    'field_omeda_download_attr_id',
                    'field_omeda_product_ids',
                    'field_omeda_promo_code',
                    'field_pull_quote',
                    'field_pullquote',
                    'field_top_copy',
                    'field_sub_title',
                    'field_app_more_information_link',
                    'field_application_case_history',
                    'field_platforms_os',
                    'field_video_resources', // Exist only on apps, part of the custom data presentation

                    'field_issue_date', // Issue date + page num appear to be references to print scheduling
                    'field_page_num',   // but don't contain enough data to map.


                    // 'field_wir_sponsor',
                    'field_youtube_uploads_id',
                    // 'field_youtube_username',
                    'field_youtube_username_override',

                    // Renamed fields, remove to cleanup
                    'nid',
                    'uid',
                    'title',
                    'field_deckhead',
                    'field_image',
                    'field_article_images',
                    'changed',
                    'field_byline',
                    'field_author_title',
                    // 'field_sub_podcasts',
                    // 'field_whitepaper',
                    // 'field_white_paper',     // Exist on Videos, contain youtube links??
                ],
                '_id'       => 'nid',
                'name'      => 'title',
                'status'    => 'status',
                'createdBy' => 'uid',
                'updatedBy' => 'revision_uid',
                'created'   => 'created',
                'updated'   => 'changed',
                'published' => 'created',
            ],
            'leadership'    => [
                'term_fields'  => [
                    'categories_control_prod',
                    'categories_int_equip',
                    'categories_technologies',
                ],
                'map'   => [
                    '2_1' => '33396',
                    '2_2' => '33389',
                    '2_3' => '33387',
                    '2_176' => '33387',
                    '2_4' => '33387',
                    '2_5' => '33387',
                    '2_6' => '33387',
                    '2_7' => '33387',
                    '2_8' => '33387',
                    '2_9' => '33393',
                    '2_10'  => '33402',
                    '2_12'  => '33400',
                    '2_67'  => '33390',
                    '2_13'  => '33395',
                    // '2_261' => '',
                    '3_212' => '33388',
                    // '3_19'  => '',
                    // '3_25'  => '',
                    // '3_16'  => '',
                    '3_59'  => '33394',
                    '3_202' => '33397',
                    '3_21'  => '33398',
                    // '3_24'  => '',
                    // '3_15'  => '',
                    // '3_86'  => '',
                    // '3_22'  => '',
                    // '3_17'  => '',
                    '3_18'  => '33401',
                    // '3_20'  => '',
                    // '3_23'  => '',
                    '3_207' => '33403',
                    // '11_62' => '',
                    // '11_192'  => '',
                    '11_60' => '33384',
                    '11_61' => '33385',
                    '11_63' => '33391',
                    '11_221'  => '33392',
                    // '11_226'  => '',
                    // '11_182'  => '',
                    // '11_197'  => '',
                    '11_187'  => '33404',
                ]
            ]
        ],
        'pfw' => [
            'name'      => 'ProFood World',
            'database'  => 'drupal_pmmi_pfw',
            'uri'       => 'https://www.profoodworld.com',
            'Issue'     => [
                'magazine' => 'Magazine\\Issue',
            ],
            'Taxonomy'  => [
                // Shared/common
                'Company type'                  => 'Taxonomy\Bin',
                'Media Property'                => 'Taxonomy\Bin',
                'Source type'                   => 'Taxonomy\Bin',
                'Subtype'                       => 'Taxonomy\Bin',
                'Coverage type'                 => 'Taxonomy\Coverage',
                'Tags'                          => 'Taxonomy\Tag',
                'Machinery'                     => 'Taxonomy\Machinery',
                'Materials'                     => 'Taxonomy\Material',
                // PFW-specific
                'Department'                    => 'Taxonomy\Bin',
                'Article subtype'               => 'Taxonomy\Bin',
                'Leadership Categories'         => 'Taxonomy\Bin',
                'Leadership Session'            => 'Taxonomy\Bin',
                'Global Company Brands'         => 'Taxonomy\Bin',
                'Global Company Industries'     => 'Taxonomy\Bin',
                'Advertiser product'            => 'Taxonomy\Category',
                'Topic'                         => 'Taxonomy\Topic',
            ],
            'Content'   => [
                'article'                   => 'Website\Content\Article',
                'page'                      => 'Website\Content\Page',
                'company'                   => 'Website\Content\Company',
                'registration_form'         => 'Website\Content\Document',
                'video'                     => 'Website\Content\Video',
                'webinar_registration'      => 'Website\Content\Webinar',
                'playbook'                  => 'Website\Content\Document',
                'person'                    => 'Website\Content\Contact',

                'bi_library_article'        => 'Website\Content\Document',  // Gated download+form
                // 'bi_library_form',
                'event'                     => 'Website\Content\Event',
                // 'leadership_data_card',
                // 'leadership_online_profile',
                // 'leadership_print_profile',
            ],
            'Section'   => [],
            'structure' =>  [
                'stripFields'   => [
                    // These fields will be removed from nodes before being written to mongo
                    'vid',
                    'log',
                    'uuid',
                    'tnid',
                    'cid',                          // comment id
                    'translate',
                    'print_html_display',
                    'print_html_display_comment',
                    'print_html_display_urllist',
                    'last_comment_uid',
                    'last_comment_name',
                    'last_comment_timestamp',
                    'revision_timestamp',           // looks to be same as 'changed' which we are using
                    'revision_uid',
                    'language',                     // language value, (und default)
                    'comment',
                    'comment_count',
                    'promote',
                    'sticky',
                    'vuuid',
                    'rdf_mapping',
                    'path',
                    'metatags',
                    'data',
                    'picture',
                    //'premium_content','comment_count','picture','data'  // other fields I see but leaving for now
                    //'moderate','format','feed','field_priority','field_leagcy_id','rdf_mapping','metatags','field_legacy_article_id');  // fields in old code, but not seen so far in hci
                    'field_360_multi_upload',
                    'field_360_images_reverse',
                    'field_360_magic_plugin',
                    'field_360_magic_plugin_columns',
                    'field_360_magic_plugin_rows',
                    'field_360_images',
                    'field_360_fc_large',
                    'field_gallery_360_field_location',
                    'field_allterms',   // @todo handle in taxonomy segment
                    'field_related',
                    'field_pop_up_registration',
                    'field_joomla_id',
                    'field_accela_id',
                    'field_duplicate',
                    'field_accelaworks_billcode',
                    'field_article_length',
                    'field_app_sponsor_news',
                    'field_brand_override',
                    'field_master_accelaworks_id',
                    'field_master_leadworks_id',
                    'field_form_header',

                    'field_post_launch_banner',
                    'field_pre_launch_banner',
                    'field_promoted',
                    'field_show_site_logo',
                    'field_silverpop_program_id',
                    'field_smg_pop_viddler',
                    'field_social_media_watch',
                    'field_sponsor_links',
                    'field_sponsor_logo',
                    'field_stage_one_form',
                    'field_vocab_primary_industry',
                    'field_vocab_primary',

                    'field_waywire_playlist_id',
                    'field_waywire_tag',
                    'field_waywire_video',
                    'field_webtracking_name',
                    'field_updated_on',
                    'field_top_copy',
                    'field_legacy',
                    'field_crosspost_to_pfw',
                    'field_reporting_from',
                    'webform',
                    'field_sales_reps', // no data

                    // Fields that may be important later, but exist in `legacy.raw`
                    'field_viddler_id',
                    'field_sponsor_expiration',
                    'field_omeda_behavior_ids',
                    'field_omeda_deployment_type_ids',
                    'field_omeda_download_attr_id',
                    'field_omeda_product_ids',
                    'field_omeda_promo_code',
                    'field_pull_quote',
                    'field_pullquote',
                    'field_top_copy',
                    'field_sub_title',
                    'field_app_more_information_link',
                    'field_application_case_history',
                    'field_platforms_os',
                    'field_video_resources', // Exist only on apps, part of the custom data presentation

                    'field_issue_date', // Issue date + page num appear to be references to print scheduling
                    'field_page_num',   // but don't contain enough data to map.


                    // 'field_wir_sponsor',
                    'field_youtube_uploads_id',
                    // 'field_youtube_username',
                    'field_youtube_username_override',

                    // Renamed fields, remove to cleanup
                    'nid',
                    'uid',
                    'title',
                    'field_deckhead',
                    'field_image',
                    'field_article_images',
                    'changed',
                    'field_byline',
                    'field_author_title',
                    // 'field_sub_podcasts',
                    // 'field_whitepaper',
                    // 'field_white_paper',     // Exist on Videos, contain youtube links??
                ],
                '_id'       => 'nid',
                'name'      => 'title',
                'status'    => 'status',
                'createdBy' => 'uid',
                'updatedBy' => 'revision_uid',
                'created'   => 'created',
                'updated'   => 'changed',
                'published' => 'created',
            ],
            'leadership'    => [
                'term_fields'  => [
                    'categories',
                ],
                'map'   => [
                    '29_2218' => '33436',
                    '29_1163' => '33437',
                    '29_1196' => '33438',
                    '29_1179' => '33439',
                    '29_1161' => '33440',
                    // '29_3826' => '',
                    '29_1164' => '33441',
                    '29_1187' => '33442',
                    '29_1165' => '33443',
                    // '29_2219' => '',
                    '29_2215' => '33444',
                    '29_1167' => '33445',
                    '29_1168' => '33446',
                    // '29_1205' => '',
                    '29_1169' => '33447',
                    '29_1170' => '33448',
                    '29_1171' => '33449',
                    '29_1199' => '33450',
                    '29_1172' => '33451',
                    '29_1173' => '33452',
                    // '29_2213' => '',
                    '29_2212' => '33453',
                    '29_1197' => '33454',
                    '29_1174' => '33455',
                    '29_2211' => '33456',
                    '29_1198' => '33457',
                    '29_1175' => '33458',
                    '29_1180' => '33459',
                    '29_1176' => '33460',
                    '29_1177' => '33461',
                    '29_1208' => '33462',
                    '29_3796' => '33463',
                    '29_1178' => '33464',
                    '29_1181' => '33465',
                    '29_1182' => '33466',
                    '29_1192' => '33467',
                    '29_1183' => '33468',
                    '29_1184' => '33469',
                    '29_3801' => '35141',
                    '29_2207' => '33470',
                    '29_1195' => '33471',
                    '29_1186' => '33472',
                    '29_1204' => '35142',
                    '29_2214' => '33473',
                    '29_2217' => '33474',
                    '29_2209' => '33475',
                ]
            ]
        ],
        'pw'  => [
            'name'      => 'Packaging World',
            'database'  => 'drupal_pmmi_pw',
            'uri'       => 'https://www.packworld.com',
            'Issue'     => [
                'magazine_covers' => 'Magazine\\Issue',
            ],
            'Taxonomy'  => [
                // Shared/common
                'Company Type'                  => 'Taxonomy\Bin',
                'Media Property'                => 'Taxonomy\Bin',
                'Source type'                   => 'Taxonomy\Bin',
                'Subtype'                       => 'Taxonomy\Bin',
                'Coverage type'                 => 'Taxonomy\Coverage',
                // 'Tags'                          => 'Taxonomy\Tag',
                'Machinery'                     => 'Taxonomy\Machinery',
                'Material Type'                 => 'Taxonomy\Material',
                'Controls'                      => 'Taxonomy\Controls',
                'Package Component'             => 'Taxonomy\PackageComponent',
                'Package Feature'               => 'Taxonomy\PackageFeature',
                'Package Type'                  => 'Taxonomy\PackageType',
                // PW-specific
                'Contract packaging'            => 'Taxonomy\Bin',
                'Expo Pack Session'             => 'Taxonomy\Bin',
                'Gallery Features'              => 'Taxonomy\Bin',
                'Gallery Industry'              => 'Taxonomy\Bin',
                'Gallery Type'                  => 'Taxonomy\Bin',
                'Leadership Main Categories'    => 'Taxonomy\Bin',
                'Leadership Session'            => 'Taxonomy\Bin',
                'Line speed'                    => 'Taxonomy\Bin',
                'Machine attributes'            => 'Taxonomy\Bin',
                'Package design'                => 'Taxonomy\Bin',
                'Sustainability'                => 'Taxonomy\Bin',
                'Venue'                         => 'Taxonomy\Bin',
                'Applications'                  => 'Taxonomy\Category',
                'Expo Pack Showcase Categories' => 'Taxonomy\ExpoPackShowcaseCategory',
                'Leadership Categories'         => 'Taxonomy\LeadershipCategory',
                'Trends and Issues'             => 'Taxonomy\Topic',
            ],
            'Content'   => [
                // '360_package_spin_rotate'   => 'Website\Content\Product',
                // 'article'                   => 'Website\Content\Article',
                // 'page'                      => 'Website\Content\Page',
                'company'                   => 'Website\Content\Company',
                'registration_form'         => 'Website\Content\Document',
                'video'                     => 'Website\Content\Video',
                'webinar_registration'      => 'Website\Content\Webinar',
                'whitepaper'                => 'Website\Content\Whitepaper',
                'playbook'                  => 'Website\Content\Document',
                'podcast'                   => 'Website\Content\Podcast',
                'blog'                      => 'Website\Content\Blog',
                'mini_bant'                 => 'Website\Content\TextAd',
                'bi_library_article'        => 'Website\Content\Document',  // Gated download+form
                // 'bi_library_form',
                'webcast'                   => 'Website\Content\Webinar',
                // 'leadership_data_card',
                // 'leadership_online_profile',
                // 'leadership_print_profile',
                // 'showcase_expo_pack_profile',
                'gallery_item'              => 'Website\Content\Product',
                'photo'                     => 'Website\Content\Product',
                'slideshow'                 => 'Website\Content\MediaGallery',
            ],
            'Section'   => [],
            'structure' =>  [
                'stripFields'   => [
                    // These fields will be removed from nodes before being written to mongo
                    'vid',
                    'log',
                    'uuid',
                    'tnid',
                    'cid',                          // comment id
                    'translate',
                    'print_html_display',
                    'print_html_display_comment',
                    'print_html_display_urllist',
                    'last_comment_uid',
                    'last_comment_name',
                    'last_comment_timestamp',
                    'revision_timestamp',           // looks to be same as 'changed' which we are using
                    'revision_uid',
                    'language',                     // language value, (und default)
                    'comment',
                    'comment_count',
                    'promote',
                    'sticky',
                    'vuuid',
                    'rdf_mapping',
                    'path',
                    'metatags',
                    'data',
                    'picture',
                    //'premium_content','comment_count','picture','data'  // other fields I see but leaving for now
                    //'moderate','format','feed','field_priority','field_leagcy_id','rdf_mapping','metatags','field_legacy_article_id');  // fields in old code, but not seen so far in hci
                    'field_360_multi_upload',
                    'field_360_images_reverse',
                    'field_360_magic_plugin',
                    'field_360_magic_plugin_columns',
                    'field_360_magic_plugin_rows',
                    'field_360_images',
                    'field_360_fc_large',
                    'field_gallery_360_field_location',
                    'field_allterms',   // @todo handle in taxonomy segment
                    'field_related',
                    'field_pop_up_registration',
                    'field_joomla_id',
                    'field_accela_id',
                    'field_duplicate',
                    'field_accelaworks_billcode',
                    'field_article_length',
                    'field_app_sponsor_news',
                    'field_brand_override',
                    'field_master_accelaworks_id',
                    'field_master_leadworks_id',
                    'field_form_header',

                    'field_post_launch_banner',
                    'field_pre_launch_banner',
                    'field_promoted',
                    'field_show_site_logo',
                    'field_silverpop_program_id',
                    'field_smg_pop_viddler',
                    'field_social_media_watch',
                    'field_sponsor_links',
                    'field_sponsor_logo',
                    'field_stage_one_form',
                    'field_vocab_primary_industry',
                    'field_vocab_primary',

                    'field_waywire_playlist_id',
                    'field_waywire_tag',
                    'field_waywire_video',
                    'field_webtracking_name',
                    'field_updated_on',
                    'field_top_copy',
                    'field_legacy',
                    'field_crosspost_to_pfw',
                    'field_reporting_from',
                    'webform',
                    'field_sales_reps', // no data

                    // Fields that may be important later, but exist in `legacy.raw`
                    'field_viddler_id',
                    'field_sponsor_expiration',
                    'field_omeda_behavior_ids',
                    'field_omeda_deployment_type_ids',
                    'field_omeda_download_attr_id',
                    'field_omeda_product_ids',
                    'field_omeda_promo_code',
                    'field_pull_quote',
                    'field_pullquote',
                    'field_top_copy',
                    'field_sub_title',
                    'field_app_more_information_link',
                    'field_application_case_history',
                    'field_platforms_os',
                    'field_video_resources', // Exist only on apps, part of the custom data presentation

                    'field_issue_date', // Issue date + page num appear to be references to print scheduling
                    'field_page_num',   // but don't contain enough data to map.


                    // 'field_wir_sponsor',
                    'field_youtube_uploads_id',
                    // 'field_youtube_username',
                    'field_youtube_username_override',

                    // Renamed fields, remove to cleanup
                    'nid',
                    'uid',
                    'title',
                    'field_deckhead',
                    'field_image',
                    'field_article_images',
                    'changed',
                    'field_byline',
                    'field_author_title',
                    // 'field_sub_podcasts',
                    // 'field_whitepaper',
                    // 'field_white_paper',     // Exist on Videos, contain youtube links??
                ],
                '_id'       => 'nid',
                'name'      => 'title',
                'status'    => 'status',
                'createdBy' => 'uid',
                'updatedBy' => 'revision_uid',
                'created'   => 'created',
                'updated'   => 'changed',
                'published' => 'created',
            ],
            'leadership'    => [
                'term_fields'  => [
                    'categories',
                ],
                'map'   => [
                    // '31_6517' => '',
                    '31_6518' => '33273',
                    '31_6519' => '33274',
                    '31_6538' => '33275',
                    '31_6562' => '33276',
                    '31_6809' => '33277',
                    '31_6520' => '33278',
                    '31_6521' => '33280',
                    '31_6564' => '33279',
                    '31_6522' => '33281',
                    '31_6523' => '33285',
                    '31_6524' => '33282',
                    // '31_7302' => '',
                    '31_6552' => '33283',
                    '31_6792' => '33284',
                    '31_6525' => '33287',
                    '31_6526' => '33286',
                    '31_7356' => '33288',
                    '31_6794' => '33290',
                    '31_6793' => '33289',
                    // '31_7336' => '',
                    '31_7351' => '33299',
                    '31_6528' => '33291',
                    '31_6529' => '33292',
                    '31_6530' => '33293',
                    '31_6532' => '33295',
                    '31_7307' => '33296',
                    '31_6810' => '33294',
                    '31_6533' => '33297',
                    '31_6553' => '33298',
                    '31_6534' => '33300',
                    '31_6569' => '33303',
                    '31_6554' => '33301',
                    '31_6555' => '33302',
                    '31_6536' => '33304',
                    '31_7346' => '33305',
                    // '31_6537' => '',
                    '31_6563' => '33308',
                    '31_6556' => '33307',
                    '31_6557' => '33309',
                    '31_6539' => '33311',
                    '31_6546' => '33312',
                    '31_6541' => '33313',
                    '31_6558' => '33310',
                    '31_6542' => '33314',
                    '31_6811' => '33315',
                    '31_6544' => '33317',
                    '31_6797' => '33316',
                    // '31_6547' => '',
                    '31_6549' => '33319',
                    '31_6550' => '33321',
                    '31_6812' => '33320',
                    '31_6813' => '33322',
                    // '31_6814' => '',
                ]
            ]
        ],
        'sc'  => [
            'name'      => 'Serialization Countdown',
            'database'  => 'drupal_pmmi_hp',
            'uri'       => 'https://www.serializationcountdown.com',
            'Issue'     => [
                'magazine_covers' => 'Magazine\\Issue',
            ],
            'Taxonomy'  => [
                'dont'  => 'map',
                // // Shared/common
                // 'Company Type'                  => 'Taxonomy\Bin',
                // 'Media Property'                => 'Taxonomy\Bin',
                // 'Source type'                   => 'Taxonomy\Bin',
                // 'Subtype'                       => 'Taxonomy\Bin',
                // 'Coverage type'                 => 'Taxonomy\Coverage',
                // // 'Tags'                          => 'Taxonomy\Tag',
                // 'Machinery'                     => 'Taxonomy\Machinery',
                // 'Material Type'                 => 'Taxonomy\Material',
                // 'Controls'                      => 'Taxonomy\Controls',
                // 'Package Component'             => 'Taxonomy\PackageComponent',
                // 'Package Feature'               => 'Taxonomy\PackageFeature',
                // 'Package Type'                  => 'Taxonomy\PackageType',
                // // PW-specific
                // 'Contract packaging'            => 'Taxonomy\Bin',
                // 'Expo Pack Session'             => 'Taxonomy\Bin',
                // 'Gallery Features'              => 'Taxonomy\Bin',
                // 'Gallery Industry'              => 'Taxonomy\Bin',
                // 'Gallery Type'                  => 'Taxonomy\Bin',
                // 'Leadership Main Categories'    => 'Taxonomy\Bin',
                // 'Leadership Session'            => 'Taxonomy\Bin',
                // 'Line speed'                    => 'Taxonomy\Bin',
                // 'Machine attributes'            => 'Taxonomy\Bin',
                // 'Package design'                => 'Taxonomy\Bin',
                // 'Sustainability'                => 'Taxonomy\Bin',
                // 'Venue'                         => 'Taxonomy\Bin',
                // 'Applications'                  => 'Taxonomy\Category',
                // 'Expo Pack Showcase Categories' => 'Taxonomy\ExpoPackShowcaseCategory',
                // 'Leadership Categories'         => 'Taxonomy\LeadershipCategory',
                // 'Trends and Issues'             => 'Taxonomy\Topic',
            ],
            'Content'   => [
                'article'                   => 'Website\Content\Article',
                'company'                   => 'Website\Content\Company',
                'webinar_registration'      => 'Website\Content\Document',
                'video'                     => 'Website\Content\Video',
                'white_paper'               => 'Website\Content\Whitepaper',
                'page'                      => 'Website\Content\Page',
                'playbook'                  => 'Website\Content\Document',
                'podcast'                   => 'Website\Content\Podcast',
            ],
            'Section'   => [],
            'structure' =>  [
                'stripFields'   => [
                    // These fields will be removed from nodes before being written to mongo
                    'vid',
                    'log',
                    'uuid',
                    'tnid',
                    'cid',                          // comment id
                    'translate',
                    'print_html_display',
                    'print_html_display_comment',
                    'print_html_display_urllist',
                    'last_comment_uid',
                    'last_comment_name',
                    'last_comment_timestamp',
                    'revision_timestamp',           // looks to be same as 'changed' which we are using
                    'revision_uid',
                    'language',                     // language value, (und default)
                    'comment',
                    'comment_count',
                    'promote',
                    'sticky',
                    'vuuid',
                    'rdf_mapping',
                    'path',
                    'metatags',
                    'data',
                    'picture',
                    //'premium_content','comment_count','picture','data'  // other fields I see but leaving for now
                    //'moderate','format','feed','field_priority','field_leagcy_id','rdf_mapping','metatags','field_legacy_article_id');  // fields in old code, but not seen so far in hci
                    'field_360_multi_upload',
                    'field_360_images_reverse',
                    'field_360_magic_plugin',
                    'field_360_magic_plugin_columns',
                    'field_360_magic_plugin_rows',
                    'field_360_images',
                    'field_360_fc_large',
                    'field_gallery_360_field_location',
                    'field_allterms',   // @todo handle in taxonomy segment
                    'field_related',
                    'field_pop_up_registration',
                    'field_joomla_id',
                    'field_accela_id',
                    'field_duplicate',
                    'field_accelaworks_billcode',
                    'field_article_length',
                    'field_app_sponsor_news',
                    'field_brand_override',
                    'field_master_accelaworks_id',
                    'field_master_leadworks_id',
                    'field_form_header',

                    'field_post_launch_banner',
                    'field_pre_launch_banner',
                    'field_promoted',
                    'field_show_site_logo',
                    'field_silverpop_program_id',
                    'field_smg_pop_viddler',
                    'field_social_media_watch',
                    'field_sponsor_links',
                    'field_sponsor_logo',
                    'field_stage_one_form',
                    'field_vocab_primary_industry',
                    'field_vocab_primary',

                    'field_waywire_playlist_id',
                    'field_waywire_tag',
                    'field_waywire_video',
                    'field_webtracking_name',
                    'field_updated_on',
                    'field_top_copy',
                    'field_legacy',
                    'field_crosspost_to_pfw',
                    'field_reporting_from',
                    'webform',
                    'field_sales_reps', // no data

                    // Fields that may be important later, but exist in `legacy.raw`
                    'field_viddler_id',
                    'field_sponsor_expiration',
                    'field_omeda_behavior_ids',
                    'field_omeda_deployment_type_ids',
                    'field_omeda_download_attr_id',
                    'field_omeda_product_ids',
                    'field_omeda_promo_code',
                    'field_pull_quote',
                    'field_pullquote',
                    'field_top_copy',
                    'field_sub_title',
                    'field_app_more_information_link',
                    'field_application_case_history',
                    'field_platforms_os',
                    'field_video_resources', // Exist only on apps, part of the custom data presentation

                    'field_issue_date', // Issue date + page num appear to be references to print scheduling
                    'field_page_num',   // but don't contain enough data to map.


                    // 'field_wir_sponsor',
                    'field_youtube_uploads_id',
                    // 'field_youtube_username',
                    'field_youtube_username_override',

                    // Renamed fields, remove to cleanup
                    'nid',
                    'uid',
                    'title',
                    'field_deckhead',
                    'field_image',
                    'field_article_images',
                    'changed',
                    'field_byline',
                    'field_author_title',
                    // 'field_sub_podcasts',
                    // 'field_whitepaper',
                    // 'field_white_paper',     // Exist on Videos, contain youtube links??
                ],
                '_id'       => 'nid',
                'name'      => 'title',
                'status'    => 'status',
                'createdBy' => 'uid',
                'updatedBy' => 'revision_uid',
                'created'   => 'created',
                'updated'   => 'changed',
                'published' => 'created',
            ],
            'leadership'    => [
                'term_fields'  => [],
                'map'   => []
            ]
        ],
    ];
}
